version: '3.7'

services:

  maria_db:
    container_name: maria_db
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test1234
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test1234
      - MYSQL_DATABASE=testdb
      - MYSQL_HOST=maria_db
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  app:
    container_name: app
    image: acecic82/auction-service:0.0
    build:
      context: ./app

    environment:
      - MYSQL_HOST=maria_db
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test1234
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=test1234
    ports:
      - 8080:8080
    depends_on:
      - maria_db
    links:
      - maria_db
    restart: always

