spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mariadb://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:testdb}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER:test}
    password: ${MYSQL_PASSWORD:test1234}
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true

    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false

  flyway:
    baseline-on-migrate: true # flyway_schema_history 테이블을 자동으로 생성할지 여부
    baseline-version: 0 # 최초 버전 정보

  redis:
    port: 6379
    host: localhost

# JPA 쿼리 파라미터 확인
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
