spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: test
    password: test1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        show_sql: true
        format_sql: true

    database-platform: org.hibernate.dialect.MariaDBDialect

  flyway:
    baseline-on-migrate: true # flyway_schema_history 테이블을 자동으로 생성할지 여부
    baseline-version: 0 # 최초 버전 정보