spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: test
    password: test1234
    driver-class-=name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect