INSERT INTO category(name) VALUE ('패션의류');
INSERT INTO category(name) VALUE ('패션잡화');
INSERT INTO category(name) VALUE ('유아용품');
INSERT INTO category(name) VALUE ('가구,인테리어');
INSERT INTO category(name) VALUE ('취미');
INSERT INTO category(name) VALUE ('디지털기기');
INSERT INTO category(name) VALUE ('스포츠');
INSERT INTO category(name) VALUE ('뷰티');
INSERT INTO category(name) VALUE ('가전');
INSERT INTO category(name) VALUE ('도서');
INSERT INTO category(name) VALUE ('기타 ');
